env:
  browser: true
  es2020: true
  node: true
extends:
  - 'plugin:react/recommended'
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  comma-dangle: 0
  max-len:
    - error
    - code: 120
  semi: 1
  require-jsdoc: 0
  react/prop-types: 0
  react/react-in-jsx-scope: 0
